# Generated by Django 5.1.3 on 2024-11-20 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('BMW', 'Bmw'), ('Audi', 'Audi'), ('Mercedes', 'Mercedes'), ('Volvo', 'Volvo'), ('Nissan', 'Nissan'), ('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Bugatti', 'Bugatti'), ('Lamborghini', 'Lamborghini'), ('Mazda', 'Mazda')], max_length=20)),
                ('model', models.CharField(choices=[('M8', 'M8'), ('M3', 'M30'), ('RSQ5', 'Rsq5'), ('Q8', 'Q8'), ('Brabus', 'Brabus'), ('CLS350', 'Cls350'), ('XC90', 'Xc90'), ('Qashqai', 'Qashqai'), ('Camry', 'Camry'), ('Civic', 'Civic'), ('Veyron', 'Veyron'), ('Urus', 'Urus'), ('CX-60', 'Cx60')], max_length=20)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)])),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000)])),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'car_application',
            },
        ),
    ]
