# Generated by Django 5.1.3 on 2024-11-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_car_ad', '0002_caradmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='caradmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='storage'),
        ),
        migrations.AlterField(
            model_name='caradmodel',
            name='model',
            field=models.CharField(choices=[('M8', 'M8'), ('M3', 'M30'), ('RSQ7', 'Rsq7'), ('Q8', 'Q8'), ('Brabus', 'Brabus'), ('CLS350', 'Cls350'), ('XC90', 'Xc90'), ('Qashqai', 'Qashqai'), ('Camry', 'Camry'), ('Civic', 'Civic'), ('Veyron', 'Veyron'), ('Urus', 'Urus'), ('CX-60', 'Cx60')], max_length=20),
        ),
    ]
