# Generated by Django 5.1.3 on 2024-11-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_car_ad', '0004_remove_caradmodel_photo_carphotomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='caradmodel',
            name='is_active_ad',
            field=models.BooleanField(default=False),
        ),
    ]
