# Generated by Django 5.1.3 on 2024-11-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_car_ad', '0005_caradmodel_is_active_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='caradmodel',
            name='check_count',
            field=models.IntegerField(default=0),
        ),
    ]
