# Generated by Django 5.1.3 on 2024-12-03 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_car_ad', '0006_caradmodel_check_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caradmodel',
            name='price',
            field=models.CharField(help_text='Acceptable input options: 10 UAH or 100 USD or 100.50 EUR', max_length=20, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d{1,2})? (UAH|USD|EUR)$', 'Acceptable input options: 10 UAH or 100 USD or 100.50 EUR')]),
        ),
    ]
